spring:
  profiles:
    active: dev
  rabbitmq:
    host:  paascloud-mq-rabbit
    port: 15672
    username: '{cipher}AQAUzETTu3sFLLArYkx8OKpGiMjeqNLGgLJpR5cPS8qEZlQm3bHOTImSNO2j1ibDStJpvQ6YLRQ57RAQYISwqiI7df395E3KjqAHxo3rjfeKh5GiU9bRLI2on0vglZ619nTwrTRewm/N6YKaqtuxF0lI6pzK8AttL05HcNklz46wegQ109jTdn/CYOC0Qwd/NO6PXwv73969Xsud9oVN/YSH/Rf2jv+dZFAaFTBhHPkb4V6OBliXfuVBcF+aGpcYg+fuFODyfNNvjnFGHHRln3JNzULeDJ58GXLEraPbq+iN8fzkQF0edFCy0F95o/LiBhVo3TDuQE0GZUkCUjmMJr5JL4YVcALKnF2r9nGmLxcjA2622cW8N0j75C1Qhdz7KnU='
    password: '{cipher}AQAUzETTu3sFLLArYkx8OKpGiMjeqNLGgLJpR5cPS8qEZlQm3bHOTImSNO2j1ibDStJpvQ6YLRQ57RAQYISwqiI7df395E3KjqAHxo3rjfeKh5GiU9bRLI2on0vglZ619nTwrTRewm/N6YKaqtuxF0lI6pzK8AttL05HcNklz46wegQ109jTdn/CYOC0Qwd/NO6PXwv73969Xsud9oVN/YSH/Rf2jv+dZFAaFTBhHPkb4V6OBliXfuVBcF+aGpcYg+fuFODyfNNvjnFGHHRln3JNzULeDJ58GXLEraPbq+iN8fzkQF0edFCy0F95o/LiBhVo3TDuQE0GZUkCUjmMJr5JL4YVcALKnF2r9nGmLxcjA2622cW8N0j75C1Qhdz7KnU='
  redis:
    host: paascloud-db-redis
    password: 123456
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 10
    max-active: 20
    test-on-borrow: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@paascloud-eureka:8761/eureka/
paascloud:
  server:
    eureka:
      port: 8761
      hostname: paascloud-eureka
      serviceUrl: http://root:root@paascloud-eureka:8761/eureka/
    discovery:
      port: 8080
      hostname: paascloud-discovery
      serviceUrl: http://admin:admin@paascloud-discovery:8080
    gateway:
      port: 80
      hostname: paascloud-gateway
    monitor:
      port: 8010
      hostname: paascloud-monitor
      serviceUrl: http://paascloud-monitor:8010
    zipkin:
      port: 8020
      hostname: paascloud-zipkin
      serviceUrl: http://paascloud-zipkin:8020
    provider:
      ehc:
        port: 8040
        hostname: paascloud-provider-ehc
      mdc:
        port: 8030
        hostname: paascloud-provider-mdc
      omc:
        port: 8050
        hostname: paascloud-provider-omc
      opc:
        port: 8070
        hostname: paascloud-provider-opc
      ptc:
        port: 8060
        hostname: paascloud-provider-ptc
      uac:
        port: 8000
        hostname: paascloud-provider-uac
    web:
      mall:
        port: 9000
        hostname: paascloud-web-mall
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  mail:
    host: smtp.sina.com
    username: '{cipher}AQCnShBQfTTW25BVv2FOt3TbWVKWqy0TD+2D9V0NDCSTBvf9zSOuy3U0I8vOoHVlqDW48gCJWstpbvHkD3Mk+ioldtkw1XDBvD5IgP4f6zodAIypP97Ch1C+mXQ0QHoMqEghjPVT9vqlAKNKZqca7yiEswiiBvQefbqTJFOyfKpeMNcDKEBfEnWzEmnk4zQsDHeqEaXfROIhzWbMhfBK7tw1HeDZ6+tx4iXCa/K7hgST5d2n8ebY1dT/VdKsgrSSst+mKu9G5uiscnaxo1FULE7gclcUowWePA+6Hs40S9g9RVVt/SH3FiipeZkkKjfw7u5AzvfRj1qofT3Yg7q1MvQthH6XB6Rb3V9chSfMNsfMj7KrHAOstg9aZ7sMIjWAjS1TnNDbIWLuqy2667rCjzOz'
    password: '{cipher}AQAvF9BZKUSyj3UIESjeNO6VO5agewN0XECrh6JtlEq/Yi4UG442ykQdJTg+ScwiCMK0cto5aVt3i2OgjiBSxvqI4reyr8xoReyIamfymmsDJC13FERKpvxDWETfVJNJ7ndm3y3NZ9zr1msYYGMhwYmVC2hbv4pZGFY1S69XZ/sJ351fZ3KRTQeE3ws6n5MjCdR66kJ9FH3gEy5sU8LOctUohYqwZiIUs3aKroDxgMfqzcKe00BuCFvcRjWa8a+MM6SsOl7K7ebvgS3kofjJGD1hemxPYR0aMVyDDJf/Bf5vgOMw/fQFErBja2uM3iWMqIKipbnfiB+/rQVEowqu95odF6ojBv3pT/b8x5AiDTxVQL5uAjxktTbDzV5333Mq+naQuy8ila6OF+vRJCed7aKe'
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2500
          starttls:
            enable: true
            required: true
  aliyun:
    key:
      accessKeyId: '{cipher}AQBBQ1qiEAwamP8ObpmdvSoRbL0icdLmkrZ749LxNlumy/sYvTet6Gjo/dRlORut477G5qvESxboKnMJ7UvZXhP6zQ7wwbzusDUrZw1SWZWnMvZXcJeZGV3lmfgk0hGQAI7g/LpiEtkC3PeAHdNic4OrS/wR/rhrT1Uj+M9a6dhfmNCdrDqlHKsFqP1asX8NH/xMs/EYjn+F6hw9vqMD9fc1xJ1FqAWoSTb4Q1JUseN4Kf6GAtBgg2CH7lpNPgh6K1cGAwE9OmMxEvIU4Bmrlt8rJQQJsmbS7EbiPE8AW8dG1fZF+/e6nkLLVjAXUKFJ5YNx0AC2s4iovesxj3Vi4eFAFC2qXKnJwlPUPPEOYwF89a/hlK0jkwQd/VXWXN5gkc2tVRS1Qmw3cJTyhxpn72Rx'
      accessKeySecret: '{cipher}AQBzt+sRrZs7niVUTsdYNS5BPoSHyHpQ3Kqri2ixuSrgK8KRYmPDaTehwqb7b1FPDqmpyW43ElIbz1b5AirEVnB6KQXjVjwEY9zBFzhgx/QgRCFZd/jTWkfJ5juvghRzY6M1LWcOZXN3WppcsN+cVIJjzlhs5zZv/R13W2z+4Wa6T5+ECdGKfIN713vddH0q00pcSUnjaXmg+OlNhwv+GjphT8DLIDczNMPmQfAJALWr0pkzB+JqM/yqHmkSHb5ZL90SrEu3gPn05JTATWun52WrDyDIHcx9RV+UCVXzvBedeEK1pkGeCqalYRKlL2myqQ2tXt249M/hRrKUKGkYkZcDw9Qfrjy4YOOIUFKZd23hoAdXhSuMaKdT3TmYomvxYzQxXsRXqA9ilRntwlRq6JiS'
    rocketMq:
      namesrvAddr: paascloud-mq-rocket:9876
    sms:
      signName: 快乐学习网
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: '{cipher}AQAcYurvvvdpXINAfWP5HQEcyLCJM6vFJFV3MJRXU4sy+sWht4eR9Tov9N0nP59wjnn69x+O35hfpizy0QCV0Eot+bXE2P2EJvMaPSvL83alarlbgLyuGJ/cCqFQRJtdi/Tj8pNcq/hBT6mO1QMxSNAe37uspx4z82VFFO6JodlaksVcqUaAjnq9JZO/QGKwYSBc0EcYIlxBsmw4ci1/xZ+ks7grTUZh2cxsPjbA3Aw0FJPqWkMi/wTWEf3xpwzi6BkkdfsGh+8jZ/lT3fLH5q/MIfW6iRyhe2x6sCoDFuT5MPhNNaCNS++QFKUTAtiaB01JiLuf8N1TWi/3sPm0V++ZO3WgCyGsw/F/biJ6fUp7gf/ieqK27zFZZUJF5JpvWU8='
      domain: dysmsapi.aliyuncs.com
  qiniu:
    key:
      accessKey: '{cipher}AQA1Bqtk/Wt6Onqqx0FNSWHNr0wTzpvNOH9QMa/pa/uMz+J1v90Ci2uKKDoLHjjp61n1lLBbrweKA0s33HKWd8+kvddRSyHq9/LyxYSDbiaUIrL8M9mJAfrNA6Ft5SVZgb/goKPXGvX8QHo0lRURRdTQSfSS3qcccAsywwtFjHIv6OLBka/2moQjujHHYirqwotFOPRGxyRJ/zJ33lwmqsLhF3hVM9uJHs2Zj5tQtGFdNsoL3sQ9DW4Tmc0ZnTuOAbIzwVWE/CI9p4SflU8jbZLyJEBdsinLQD9YLOaIoSwBSpvX7ZJ2DuhZLzPrCXzmXmHTEEEOMfezs8FdjZhfG9rBW0fXQBKYMoZeOxHAQtpACd510FkfBhh29bjnfI8hnNTVYu0GzwDk0NQLvusUe/tU+X7ffgVpYAjuPjqp+u/1Pw=='
      secretKey: '{cipher}AQASeBRQA98IdqdelB1VPbWh3sKFOAXwpcDWP0alXJiM8FLoSoBI7W2celg9xs5cAkaXOipir9x5WoYGg7XrH8I5WgGnqdxgfTJjXQ4ZC4MTXPsFRoZD3cmu+7jL/QtFqpJLf1YMFQ098CR5jVkfCGsIUTMG+56JfatmnxX+p5jQUKNC607A3oCwyg3w51cPSH0P/z9azTm2O1jwlx/zJkcd+AyFXlJcNPJzui2VQNgKbncT2K1oafbTadXkQma0D2Fsf9rj6px9Dpm4D7AFOSJO02X/ZgrYk+jOmwfds4qKXXCUqASh7N/EjWvR6xs+aZ1wk5nY/+asVmrwIDJf++hRQkT3RJLkfqto0ZSbkJN5F21yUyA1j1g4SWHAfQWlXVoZFlaAOaVlFr6hbmUU0Qd85DCn0OUhg9Fi+FFSFHlvWA=='
    oss:
      privateHost: '{cipher}AQBlOWxk68skwXG/hVP3wTmX3tYvbXneOZ6YzZ+lyetnd4n7dZSym/Y3XJdaro2CG8pbkH2ZODKTvMZphL3EW2DCXyxm2yMpkavzuBM4XO0+5QUkQGIUqTXe45Xik3+ZKU6tvWK0IVpFAA/hcc5GjOBSMQhpXfuaP3QLbLwzID4Plu5sAB5j6keXw2Hrl/ShQcKDNSRIaTIrYoz92rl3CY9+9gNXR8/bR33NOwWVIbKFWwJ5M4HkWSgefAbk8G6Ya3IfKAZ3KmifKtKAgHJOJsKFZfH1uQyA7TLjasK68+Wzn8YkqjGGWawr3+X1PULLhvUyIvk2d5Xb2qG7Sk79lPidKM98lpJ6HhmMeqsB6JYAY1oXZESNz9AEKyrvq+phPzRRndtNwxtnGBROB8/8bPX+'
      publicHost: '{cipher}AQBh9gVzRJdmPY19AeeFTiScQizA/gQ8DRZHXWIgpugxls4OU73dno5BmVDaspHdImi7W8q/FmeZOlEDFuCKab8Ul1yV5YdvqV1bRompa2TWLLeIfC+bux+dMSjE9NFsRbGR46vW4cwk5HlRf/QAvrCxyilWDz3zgYGtJePySeij4hOG3aQA0tyjmbGdRq9nLELhlT6oSyyhXwOX+t4aF1dXqstam1/eF3B1tRshRnPaoDp2cOVxcFIxokBPLsfX+QtDbNAJlBUe78uEXWakyn/YkqCjeTm/dU/cds1hS7awkl7ohnNx1+Y6vySFe+SVzAby/JjMEPx2YfeIyw35Ezf5ruZnShCyct5tfLvPkWLixVueEvZNQedEBdVPVyxULAML7jbAHu9VpDWLqfDby8G+'
  alipay:
    callback:
      url: http://dev-api.paascloud.net/omc/pay/alipayCallback
    qrCode:
      pcPath: E:/File/alipay/QRCode
      qiniuPath: alipay/QRCode/
